import dotenv from "dotenv";
import connectDB from "../config/db.js";
import Word from "../models/word.js";

dotenv.config();

const WORDS = [
  { text: "apple", difficulty: "easy", category: "food" },
  { text: "banana", difficulty: "easy", category: "food" },
  { text: "pizza", difficulty: "easy", category: "food" },
  { text: "cookie", difficulty: "easy", category: "food" },
  { text: "ice cream", difficulty: "easy", category: "food" },
  { text: "tiger", difficulty: "easy", category: "animals" },
  { text: "dog", difficulty: "easy", category: "animals" },
  { text: "cat", difficulty: "easy", category: "animals" },
  { text: "fish", difficulty: "easy", category: "animals" },
  { text: "butterfly", difficulty: "easy", category: "animals" },
  { text: "school bus", difficulty: "easy", category: "vehicles" },
  { text: "car", difficulty: "easy", category: "vehicles" },
  { text: "bicycle", difficulty: "easy", category: "vehicles" },
  { text: "airplane", difficulty: "easy", category: "vehicles" },
  { text: "house", difficulty: "easy", category: "places" },
  { text: "beach", difficulty: "easy", category: "places" },
  { text: "tree", difficulty: "easy", category: "nature" },
  { text: "sun", difficulty: "easy", category: "nature" },
  { text: "rainbow", difficulty: "easy", category: "nature" },
  { text: "football", difficulty: "easy", category: "sports" },
  { text: "basketball", difficulty: "easy", category: "sports" },
  { text: "guitar", difficulty: "easy", category: "objects" },
  { text: "phone", difficulty: "easy", category: "objects" },
  { text: "book", difficulty: "easy", category: "objects" },
  { text: "hat", difficulty: "easy", category: "objects" },
  { text: "volcano", difficulty: "medium", category: "nature" },
  { text: "waterfall", difficulty: "medium", category: "nature" },
  { text: "mountain", difficulty: "medium", category: "nature" },
  { text: "astronaut", difficulty: "medium", category: "people" },
  { text: "pirate", difficulty: "medium", category: "people" },
  { text: "wizard", difficulty: "medium", category: "people" },
  { text: "detective", difficulty: "medium", category: "people" },
  { text: "violin", difficulty: "medium", category: "music" },
  { text: "piano", difficulty: "medium", category: "music" },
  { text: "drums", difficulty: "medium", category: "music" },
  { text: "castle", difficulty: "medium", category: "places" },
  { text: "submarine", difficulty: "medium", category: "vehicles" },
  { text: "rocket", difficulty: "medium", category: "vehicles" },
  { text: "campfire", difficulty: "medium", category: "nature" },
  { text: "snowman", difficulty: "medium", category: "objects" },
  { text: "telescope", difficulty: "medium", category: "objects" },
  { text: "skateboard", difficulty: "medium", category: "sports" },
  { text: "surfboard", difficulty: "medium", category: "sports" },
  { text: "parachute", difficulty: "hard", category: "objects" },
  { text: "lighthouse", difficulty: "hard", category: "places" },
  { text: "helicopter", difficulty: "hard", category: "vehicles" },
  { text: "dragon fruit", difficulty: "hard", category: "food" },
  { text: "skyscraper", difficulty: "hard", category: "places" },
  { text: "microscope", difficulty: "hard", category: "objects" },
  { text: "chameleon", difficulty: "hard", category: "animals" },
  { text: "octopus", difficulty: "hard", category: "animals" },
  { text: "accordion", difficulty: "hard", category: "music" },
  { text: "windmill", difficulty: "hard", category: "places" },
  { text: "firefighter", difficulty: "hard", category: "people" },
  { text: "roller coaster", difficulty: "hard", category: "places" },
  { text: "snowflake", difficulty: "hard", category: "nature" },
  { text: "elephant", difficulty: "medium", category: "animals" },
  { text: "giraffe", difficulty: "medium", category: "animals" },
  { text: "snake", difficulty: "easy", category: "animals" },
  { text: "frog", difficulty: "easy", category: "animals" },
  { text: "penguin", difficulty: "medium", category: "animals" },
  { text: "kangaroo", difficulty: "hard", category: "animals" },
  { text: "lion", difficulty: "medium", category: "animals" },
  { text: "monkey", difficulty: "easy", category: "animals" },
  { text: "spider", difficulty: "easy", category: "animals" },
  { text: "crab", difficulty: "medium", category: "animals" },
  { text: "seahorse", difficulty: "hard", category: "animals" },
  { text: "turtle", difficulty: "easy", category: "animals" },
  { text: "bear", difficulty: "medium", category: "animals" },
  { text: "panda", difficulty: "medium", category: "animals" },
  { text: "owl", difficulty: "medium", category: "animals" },
  { text: "hamburger", difficulty: "medium", category: "food" },
  { text: "hot dog", difficulty: "easy", category: "food" },
  { text: "sandwich", difficulty: "easy", category: "food" },
  { text: "taco", difficulty: "medium", category: "food" },
  { text: "sushi", difficulty: "hard", category: "food" },
  { text: "spaghetti", difficulty: "hard", category: "food" },
  { text: "donut", difficulty: "easy", category: "food" },
  { text: "popcorn", difficulty: "medium", category: "food" },
  { text: "watermelon", difficulty: "easy", category: "food" },
  { text: "strawberry", difficulty: "medium", category: "food" },
  { text: "cheese", difficulty: "easy", category: "food" },
  { text: "pineapple", difficulty: "medium", category: "food" },
  { text: "egg", difficulty: "easy", category: "food" },
  { text: "bread", difficulty: "easy", category: "food" },
  { text: "pancake", difficulty: "medium", category: "food" },
  { text: "train", difficulty: "easy", category: "vehicles" },
  { text: "truck", difficulty: "easy", category: "vehicles" },
  { text: "motorcycle", difficulty: "medium", category: "vehicles" },
  { text: "boat", difficulty: "easy", category: "vehicles" },
  { text: "tractor", difficulty: "medium", category: "vehicles" },
  { text: "ambulance", difficulty: "medium", category: "vehicles" },
  { text: "police car", difficulty: "medium", category: "vehicles" },
  { text: "hot air balloon", difficulty: "hard", category: "vehicles" },
  { text: "bulldozer", difficulty: "hard", category: "vehicles" },
  { text: "scooter", difficulty: "easy", category: "vehicles" },
  { text: "hospital", difficulty: "medium", category: "places" },
  { text: "school", difficulty: "easy", category: "places" },
  { text: "park", difficulty: "easy", category: "places" },
  { text: "library", difficulty: "medium", category: "places" },
  { text: "stadium", difficulty: "hard", category: "places" },
  { text: "bridge", difficulty: "medium", category: "places" },
  { text: "tent", difficulty: "easy", category: "places" },
  { text: "zoo", difficulty: "medium", category: "places" },
  { text: "farm", difficulty: "easy", category: "places" },
  { text: "cinema", difficulty: "medium", category: "places" },
  { text: "moon", difficulty: "easy", category: "nature" },
  { text: "star", difficulty: "easy", category: "nature" },
  { text: "cloud", difficulty: "easy", category: "nature" },
  { text: "lightning", difficulty: "medium", category: "nature" },
  { text: "tornado", difficulty: "hard", category: "nature" },
  { text: "leaf", difficulty: "easy", category: "nature" },
  { text: "flower", difficulty: "easy", category: "nature" },
  { text: "river", difficulty: "medium", category: "nature" },
  { text: "forest", difficulty: "medium", category: "nature" },
  { text: "desert", difficulty: "medium", category: "nature" },
  { text: "tennis", difficulty: "medium", category: "sports" },
  { text: "soccer", difficulty: "easy", category: "sports" },
  { text: "baseball", difficulty: "medium", category: "sports" },
  { text: "golf", difficulty: "medium", category: "sports" },
  { text: "swimming", difficulty: "medium", category: "sports" },
  { text: "boxing", difficulty: "medium", category: "sports" },
  { text: "skiing", difficulty: "hard", category: "sports" },
  { text: "bowling", difficulty: "medium", category: "sports" },
  { text: "cycling", difficulty: "medium", category: "sports" },
  { text: "volleyball", difficulty: "hard", category: "sports" },
  { text: "clock", difficulty: "easy", category: "objects" },
  { text: "computer", difficulty: "medium", category: "objects" },
  { text: "television", difficulty: "easy", category: "objects" },
  { text: "chair", difficulty: "easy", category: "objects" },
  { text: "table", difficulty: "easy", category: "objects" },
  { text: "bed", difficulty: "easy", category: "objects" },
  { text: "lamp", difficulty: "easy", category: "objects" },
  { text: "scissors", difficulty: "medium", category: "objects" },
  { text: "key", difficulty: "easy", category: "objects" },
  { text: "lock", difficulty: "medium", category: "objects" },
  { text: "crown", difficulty: "easy", category: "objects" },
  { text: "sword", difficulty: "medium", category: "objects" },
  { text: "shield", difficulty: "medium", category: "objects" },
  { text: "anchor", difficulty: "hard", category: "objects" },
  { text: "compass", difficulty: "hard", category: "objects" },
  { text: "toothbrush", difficulty: "medium", category: "objects" },
  { text: "toothpaste", difficulty: "medium", category: "objects" },
  { text: "hairbrush", difficulty: "easy", category: "objects" },
  { text: "camera", difficulty: "medium", category: "objects" },
  { text: "umbrella", difficulty: "medium", category: "objects" },
  { text: "balloon", difficulty: "easy", category: "objects" },
  { text: "kite", difficulty: "easy", category: "objects" },
  { text: "gift", difficulty: "easy", category: "objects" },
  { text: "pencil", difficulty: "easy", category: "objects" },
  { text: "pen", difficulty: "easy", category: "objects" },
  { text: "eraser", difficulty: "medium", category: "objects" },
  { text: "bucket", difficulty: "easy", category: "objects" },
  { text: "flute", difficulty: "medium", category: "music" },
  { text: "doctor", difficulty: "medium", category: "people" },
  { text: "alien", difficulty: "hard", category: "people" },
];

async function seed() {
  await connectDB();

  const unique = new Map();
  for (const entry of WORDS) {
    unique.set(entry.text.toLowerCase(), entry);
  }

  const docs = [...unique.values()];
  let inserted = 0;

  for (const doc of docs) {
    const result = await Word.updateOne(
      { text: doc.text },
      { $set: doc },
      { upsert: true },
    );
    if (result.upsertedCount > 0) inserted++;
  }

  const total = await Word.countDocuments();
  console.log(`Seed complete. New: ${inserted}, Total in DB: ${total}`);
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
